#Main deployment for application

name: Release Pipeline for vulnerable WebApp - Ekoparty CS&DSO

on:     
  push:
    branches:   
      - master

  workflow_dispatch:
  workflow_call:

jobs:

  init:
    name: Init
    uses: ./.github/workflows/init.yml

  security_sast:
      name: SAST Stage using Snyk
      needs: init
      uses: ./.github/workflows/security-sast.yml

  build_and_deploy:
      name: Build and Deploy Stage
      needs: security_sast
      uses: ./.github/workflows/build-and-deploy.yml      

  security_dast:
      name: DAST Analysis
      needs: build_and_deploy
      uses: ./.github/workflows/security-dast.yml    
