#DAST Stage - Post app deployment in Heroku

on:
  workflow_call:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Application DAST Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'https://elianasanabria-ekoparty-csdso-4549750a5266.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
